### ISSUE TITLE
Steps to flip the switch

### ISSUE THREAD

**Issue by craigspaeth** [artsy/force-merge#1]
- [x] Optionally consolidate Force's asset packages to reduce deploy time
- [x] Add the CONTRIBUTING and README docs for this new world
- [x] Create force staging/production buckets + cloudfront urls in the new S3 account
- [x] Add deploy script to npm scripts (use `git remote add heroku ...` in Circle later to differentiate staging/production) 
- [x] Wait a week :crossed_fingers: QA + builds pass consistently
- [x] Pick a day and announce it as the _freeze on Force & MG_ day 
- [x] 😮  💨 
- [x] Start a new Force branch, empty it out and copy over this code, then run merge/ci.sh
- [x] Make sure `npm test` passes
- [x] Delete the merge folder
- [x] Remove desktop/ mobile/ tmp/ and package.json .env.oss etc from .gitignore
- [x] Commit, push, PR and merge to Force
- [x] Close down PRs to MG
- [x] Babysit a staging deploy
- [x] Clean out all of the config on staging to reflect the new config
- [x] Production deploy
  - [x] Get staging deploy running on Circle
  - [x] Setup production deploy > release CI build
  - [x] Ensure the new Force S3 bucket permissions are in order
  - [x] Prepare a `heroku rollback` and a big `heroku config:unset A B C && heroku config:set A=b` in your terminal
    - [x] Run the merge config script from force-merge
    - [x] Change [these](https://github.com/artsy/force-merge/blob/master/merge/config.js#L21) [variables](https://github.com/artsy/force-merge/blob/master/merge/config.js#L6) to production config
  - [x] 😮  💨 
  - [x] Run the production CI build
  - [x] Watch the build and run the config set when it finishes 
  - [x] :crossed_fingers:
  - [x] 🍾 
  - [x] Rollback production before bed time, and deploy again tomorow morning
- [x] Take down force-merge server
- [x] Writeup any steps ppl need to take now
- [x] Add Danger back in
- [ ] Replace MG with something that just 301s to www
- [x] Remove rel="alternate" tags
- [ ] Serve XML sitemap of all the m.artsy.net  URLs (with their 301s in place) and that forces google to crawl it
- [x] Switch to Yarn
- [x] Get build time down

**Comment by alloy** [comment]
Ooohhh, is that all? 😄

**Comment by craigspaeth** [comment]
Haha 😛  everything after the 😮  💨  is intended to happen in a couple hour period though. Just trying to make sure I don't forget anything.

![](https://media.giphy.com/media/oKVs1VY0MKfvO/giphy.gif)

**Comment by christine-artsy** [comment]
Oh looks like you included it already @craigspaeth! For context, adding a supplemental XML sitemap with all the m.artsy.net URLs (after 301s are in place) will essentially force search engines to register the redirects faster than old URLs falling out of the index naturally (which happens on a link-by-link basis, which is why it's slow). 

I also don't think Google has all of m.artsy.net entirely indexed (https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site:m.artsy.net) so we might be able to get away with doing this for certain templates (i.e., all /artist/ and /artwork/ pages rather than the whole site) if that's easier. Also, since articles are already responsive so we probably wouldn't have to do it for those URLs as far as I know. Thanks!

**Comment by craigspaeth** [comment]
Phew! The hard part is over, got a working staging + production with the merged codebase. Rolled back so we have no surprises while sleeping, but we'll roll forward with `heroku rollback v3380 --app=force-production` in the morning and carry on with the rest of the post-cleanup. Closing 😅

**Comment by orta** [comment]
🎉

**Comment by alloy** [comment]
Great job 👏
